### ISSUE TITLE
OCaml support

### ISSUE THREAD

**Issue by godmar** [Kattis/problemtools#115]
Suggestion.  Add an entry such as

```
ocaml:
    name: 'OCaml'
    priority: 610
    files: '*.ml'
    compile: '/usr/bin/ocamlc -o {binary} {files}'
    run: '{binary}'
```

(note this is not ready for a PR, just successfully tested on one example - someone needs to look up what other switches might be suitable for ocamlc)
